export const USER_REPOSITORY = 'USER_REPOSITORY_TOKEN';
export const USER_INFO_REPOSITORY = 'USER_INFO_REPOSITORY_TOKEN';
export const REVIEW_REPOSITORY = 'REVIEW_REPOSITORY_TOKEN';
export const GAME_REPOSITORY = 'GAME_REPOSITORY_TOKEN';
export const REVIEW_REACTS_REPOSITORY = 'REVIEW_REACTS_REPOSITORY_TOKEN';
export const SEQUELIZE = 'SEQUELIZE_TOKEN';
